package com.example.notification.notification;
import com.example.notification.audit.*; import com.example.notification.common.ApiException; import com.example.notification.security.SecurityUtils; import com.example.notification.template.*; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service public class NotificationService{
 private final NotificationRepository repo; private final TemplateRepository templates; private final TemplateRenderer renderer; private final ObjectMapper mapper; private final AuditService audit;
 public NotificationService(NotificationRepository repo,TemplateRepository templates,TemplateRenderer renderer,ObjectMapper mapper,AuditService audit){this.repo=repo;this.templates=templates;this.renderer=renderer;this.mapper=mapper;this.audit=audit;}
 @Transactional public Notification create(UUID templateId,String recipient,Map<String,Object> variables,Instant scheduledAt,String idempotencyKey){UUID tenant=SecurityUtils.tenant(); Template t=templates.findByIdAndTenantId(templateId,tenant).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Template not found")); try{renderer.render(t.getBody(),variables);renderer.render(t.getSubject(),variables);String json=mapper.writeValueAsString(variables);if(idempotencyKey==null||idempotencyKey.isBlank())idempotencyKey=UUID.randomUUID().toString();var existing=repo.findByTenantIdAndIdempotencyKey(tenant,idempotencyKey);if(existing.isPresent())return existing.get();Notification n=repo.save(new Notification(tenant,templateId,t.getChannel(),recipient,json,idempotencyKey,scheduledAt));audit.event(tenant,n.getId(),AuditEventType.CREATED,"status="+n.getStatus());return n;}catch(Exception e){if(e instanceof ApiException a)throw a;throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid variables: "+e.getMessage());}}
 public Notification get(UUID id){Notification n=repo.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Notification not found"));if(!SecurityUtils.current().isPlatformAdmin()&&!n.getTenantId().equals(SecurityUtils.tenant()))throw new ApiException(HttpStatus.FORBIDDEN,"Tenant isolation violation");return n;}
 public List<Notification> list(){return SecurityUtils.current().isPlatformAdmin()?repo.findAll():repo.findByTenantId(SecurityUtils.tenant());}
 @Transactional public Notification cancel(UUID id){Notification n=get(id);if(!(n.getStatus()==NotificationStatus.SCHEDULED||n.getStatus()==NotificationStatus.QUEUED||n.getStatus()==NotificationStatus.RETRY_PENDING))throw new ApiException(HttpStatus.CONFLICT,"Notification cannot be cancelled from state "+n.getStatus());String old=n.getStatus().name();n.cancelled();Notification saved=repo.save(n);audit.transition(n.getTenantId(),n.getId(),old,n.getStatus().name(),"cancelled");return saved;}
 public Map<String,Object> renderPayload(Notification n){try{Template t=templates.findById(n.getTemplateId()).orElseThrow();Map<String,Object> vars=mapper.readValue(n.getVariablesJson(),new TypeReference<>(){});return Map.of("subject",renderer.render(t.getSubject(),vars),"body",renderer.render(t.getBody(),vars));}catch(Exception e){throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"Could not render notification: "+e.getMessage());}}
}
